# Generated by Django 4.2.1 on 2023-05-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerPart', '0004_alter_avatar_img_developer_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='Task',
            new_name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
